events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location / {
            access_log /dev/stdout;
            error_log /dev/stderr;
            
            # Simple health check
            return 200 "Service-B (Nginx) is healthy\n";
        }

        # Simulate errors for Alertmanager testing
        location /error {
            access_log /dev/stdout;
            error_log /dev/stderr;
            return 500 "Service-B simulated error\n";
        }
    }
}
